import type {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";
import React from "react";
import styled from 'styled-components';

import ProductCard from "../src/components/ProductCard";
import { Product } from '../types';



interface IProps {
  products: Product[]
}

const Home   = ({ products }: IProps) => {
  return (
    <>
      <Head>
        <title>Rohlik Eshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductsContainer>
          {products?.map((product: Product) => {
            return <ProductCard product={product} key={product.id}></ProductCard>;
          })}
        </ProductsContainer>
      </main>

      <footer></footer>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/data");
  const data = await res.json();
  return { props: { products: data } };
};

export default Home;

const ProductsContainer = styled.div`{
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 20px;
  padding-top: 12vh;
}`